name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true

    - name: Build
      run: msbuild /m /p:Configuration=Debug WPFTrainner\WPFTrainner.sln

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WPFTrainner
        path: bin\x64\Debug\
